/**
 * Application route constants — use instead of hardcoded strings in links/redirects.
 */
export const ROUTES = {
  home: "/",
  courses: "/courses",
  cart: "/cart",
  checkout: "/checkout",
  business: "/business",
  teachers: "/teachers",
  teacherProfile: (slug: string) => `/teachers/${slug}`,
  career: "/career",
  position: "/position",
  positionJob: (jobId: string) => `/position/${jobId}`,
  contact: "/contact",
  courseCategory: (categoryId: string) => `/courses/category/${categoryId}`,
  blog: "/blog",
  blogPost: (slug: string) => `/blog/${slug}`,
  podcast: "/podcast",
  podcastEpisode: (slug: string) => `/podcast/${slug}`,
  about: "/about",
  affiliate: "/affiliate",
  help: "/help",
  helpArticle: (slug: string) => `/help/${slug}`,
  maintenance: "/maintenance",
  comingSoon: "/coming-soon",
  terms: "/terms",
  privacy: "/privacy",
  verifyCertificate: "/verify-certificate",
  auth: {
    login: "/login",
    register: "/register",
    verifyOtp: "/verify-otp",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
  },
  student: {
    root: "/student",
    courses: "/student/courses",
    courseDetails: (slug: string) => `/student/courses/${slug}`,
    courseLesson: (slug: string, lessonId = "lesson-basics-ux") =>
      `/student/courses/${slug}/lesson?lesson=${lessonId}`,
    courseLive: (slug: string, lessonId = "live-l10") =>
      `/student/courses/${slug}/live?lesson=${lessonId}`,
    courseAssignment: (slug: string, assignmentId = "live-assignment-platforms") =>
      `/student/courses/${slug}/assignment?assignment=${assignmentId}`,
    courseAssignmentFeedback: (slug: string, assignmentId = "live-assignment-platforms") =>
      `/student/courses/${slug}/assignment/feedback?assignment=${assignmentId}`,
    courseResources: (slug: string, resourceId = "live-l11") =>
      `/student/courses/${slug}/resources?resource=${resourceId}`,
    courseQuiz: (slug: string, quizId = "live-l14") =>
      `/student/courses/${slug}/quiz?quiz=${quizId}`,
    courseQuizPlay: (slug: string, quizId = "live-l14") =>
      `/student/courses/${slug}/quiz/play?quiz=${quizId}`,
    courseQuizResult: (slug: string, quizId = "live-l14") =>
      `/student/courses/${slug}/quiz/result?quiz=${quizId}`,
    courseQuizTimeOver: (slug: string, quizId = "live-l14") =>
      `/student/courses/${slug}/quiz/time-over?quiz=${quizId}`,
    courseQuizAnswers: (slug: string, quizId = "live-l14") =>
      `/student/courses/${slug}/quiz/answers?quiz=${quizId}`,
    schedule: "/student/schedule",
    resources: "/student/resources",
    workshop: "/student/workshop",
    live: "/student/live",
    assignments: "/student/assignments",
    certificates: "/student/certificates",
    wishlist: "/student/wishlist",
    notifications: "/student/notifications",
    chat: "/student/chat",
    payments: "/student/payments",
    settings: "/student/settings",
    profile: "/student/profile",
  },
  teacher: {
    root: "/teacher",
    courses: "/teacher/courses",
    courseDetails: (slug: string) => `/teacher/courses/${slug}`,
    courseLive: (slug: string, lessonId = "tm1-l1") =>
      `/teacher/courses/${slug}/live?lesson=${lessonId}`,
    schedule: "/teacher/schedule",
    resources: "/teacher/resources",
    workshop: "/teacher/workshop",
    chat: "/teacher/chat",
    payments: "/teacher/payments",
    settings: "/teacher/settings",
    support: "/teacher/support",
    live: "/teacher/live",
    students: "/teacher/students",
    analytics: "/teacher/analytics",
  },
  admin: {
    root: "/admin",
    users: "/admin/users",
    learners: "/admin/users/learners",
    students: "/admin/users/students",
    teachers: "/admin/users/teachers",
    admins: "/admin/users/admins",
    courses: "/admin/courses",
    categories: "/admin/categories",
    promos: "/admin/promos",
    workshop: "/admin/workshop",
    transactions: "/admin/transactions",
    quiz: "/admin/quiz",
    analytics: "/admin/analytics",
    blog: "/admin/blog",
    support: "/admin/support",
    settings: "/admin/settings",
  },
} as const;
