/**
 * Application route constants — use instead of hardcoded strings in links/redirects.
 */
export const ROUTES = {
  home: "/",
  courses: "/courses",
  cart: "/cart",
  checkout: "/checkout",
  business: "/business",
  teachers: "/teachers",
  teacherProfile: (slug: string) => `/teachers/${slug}`,
  career: "/career",
  position: "/position",
  positionJob: (jobId: string) => `/position/${jobId}`,
  contact: "/contact",
  courseCategory: (categoryId: string) => `/courses/category/${categoryId}`,
  blog: "/blog",
  blogPost: (slug: string) => `/blog/${slug}`,
  podcast: "/podcast",
  podcastEpisode: (slug: string) => `/podcast/${slug}`,
  about: "/about",
  affiliate: "/affiliate",
  help: "/help",
  helpArticle: (slug: string) => `/help/${slug}`,
  maintenance: "/maintenance",
  auth: {
    login: "/login",
    register: "/register",
    verifyOtp: "/verify-otp",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
  },
  student: {
    root: "/student",
    courses: "/student/courses",
    live: "/student/live",
    assignments: "/student/assignments",
    certificates: "/student/certificates",
    wishlist: "/student/wishlist",
    chat: "/student/chat",
    payments: "/student/payments",
    settings: "/student/settings",
    profile: "/student/profile",
  },
  teacher: {
    root: "/teacher",
    courses: "/teacher/courses",
    live: "/teacher/live",
    students: "/teacher/students",
    analytics: "/teacher/analytics",
    chat: "/teacher/chat",
    settings: "/teacher/settings",
  },
  admin: {
    root: "/admin",
    users: "/admin/users",
    courses: "/admin/courses",
    payments: "/admin/payments",
    analytics: "/admin/analytics",
    support: "/admin/support",
    settings: "/admin/settings",
  },
} as const;
